name: pyhc-latest
channels:
  - conda-forge
dependencies:
  - astropy
  - bokeh
  - cartopy
  - gfortran  # needed for ffnet dependency of spacepy
  - jupyter-book
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - plasmapy
  - python
  - scipy
  - sunpy
  - watermark
  - xarray
  - pip:
    - cdflib
    - hapiclient
    - hapiplot
    - kamodo
    - pysat
    - pyspedas
    - pytplot
    - spacepy
